### ISSUE TITLE
嗯~一些问题如下

### ISSUE THREAD

**Issue by ruidps** [CthuWork/NewGui-for-Minecraft#2]
1.看是15年的项目，逛mcbbs时候发现了，试用发现版本检查和联网公告功能失效了。暂时不知道什么原因，浏览器可以访问到update.html文件。
2.翻源码看看，java，没学过，，远程借朋友java开发环境用了，应该是缺api打包出来没用，之前没学过java也没开发过mod。是forge吗？版本是什么？可以了解一下吗？
谢~

**Comment by Android-KitKat** [comment]
这个是Forge的MOD。
不过他们都开坑不填坑的(滑稽)。

**Comment by Android-KitKat** [comment]
这个是Forge的MOD。
不过他们都开坑不填坑的(滑稽)。

这个MOD的原理就是先把原版的`net.minecraft.client.gui.GuiMainMenu`这个类复制。
然后修改复制的代码，给界面加特技，加公告之类的。
在MOD中监听`net.minecraftforge.client.event.GuiOpenEvent`事件。
用instanceof关键字判断GuiOpenEvent的gui变量是否是GuiMainMenu。
如果是则赋值为自己复制修改的类。

还有，如果你尝试直接编译这个仓库的代码。
应该是会出错的，因为那个人在最后一个提交把import关键字都去掉了。
你得看这个提交才行https://github.com/CthuWorkOrganization/NewGui-for-Minecraft/commit/21ba56016fc788eb3e99618642bba94ac915df26。
不要问我为什么要去掉，这个你得去问他。

**Comment by Android-KitKat** [comment]
这个是Forge的MOD。
不过他们都开坑不填坑的(滑稽)。

这个MOD的原理就是先把原版的`net.minecraft.client.gui.GuiMainMenu`这个类复制。
然后修改复制的代码，给界面加特技，加公告之类的。
在MOD中监听`net.minecraftforge.client.event.GuiOpenEvent`事件。
用instanceof关键字判断GuiOpenEvent的gui变量是否是GuiMainMenu。
如果是则赋值为自己复制修改的类。

还有，如果你尝试直接编译这个仓库的代码。
应该是会出错的，因为那个人在最后一个提交 https://github.com/CthuWorkOrganization/NewGui-for-Minecraft/commit/91044c33421962bc3d5911906825fe520eee7597 把import关键字都去掉了。
所以你得看这个提交才行 https://github.com/CthuWorkOrganization/NewGui-for-Minecraft/commit/21ba56016fc788eb3e99618642bba94ac915df26 。
不要问我为什么要去掉，这个你得去问他 @BakaSea 。
